# This Config is just for etherpad service

version: "3.3"

services:
  # Tailchat 云文档
  tailchat-docs:
    build:
      context: .
    image: tailchat-docs
    env_file: docker-compose.env
    # TODO: 临时方案
    external_links:
      - tailchat-server-cloudbase-nightly_mongo_1:mongo
      - tailchat-server-cloudbase-nightly_redis_1:redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tailchat-docs-web.rule=PathPrefix(`/tc-docs-web/`)"
      - "traefik.http.services.tailchat-docs-web.loadbalancer.server.port=22010"
      - "traefik.http.routers.tailchat-docs-web.middlewares=tailchat-docs-web-prefix"
      - "traefik.http.middlewares.tailchat-docs-web-prefix.stripprefix.prefixes=/tc-docs-web/"
    networks:
      - tailchat

  tailchat-docs-etherpad:
    build:
      context: ./etherpad-lite
    image: tailchat-docs-etherpad
    env_file:
      - "docker-compose.env"
      - ".ep.env"
    external_links:
      - tailchat-server-cloudbase-nightly_mongo_1:mongo
    environment:
      DB_TYPE: mongodb
      DB_URL: mongodb://mongo:27017/tailchat_ep
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ep.rule=PathPrefix(`/ep/`)"
      - "traefik.http.services.ep.loadbalancer.server.port=9001"
      - "traefik.http.routers.ep.middlewares=ep-prefix"
      - "traefik.http.middlewares.ep-prefix.stripprefix.prefixes=/ep/"
    networks:
      - tailchat

networks:
  tailchat:
    external:
      name: tailchat-internal
