# This Config is just for etherpad service

version: "3.3"

services:
  tailchat-docs-web:
    image: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tailchat-docs-web.rule=PathPrefix(`/tc-docs-web/`)"
      - "traefik.http.services.tailchat-docs-web.loadbalancer.server.port=80"
    volumes:
      - ./public:/usr/share/nginx/html/tc-docs-web
    networks:
      - tailchat

  tailchat-etherpad:
    build:
      context: ./etherpad-lite
    env_file:
      - "docker-compose.env"
      - ".ep.env"
    image: tailchat-etherpad
    environment:
      DB_TYPE: mongodb
      DB_URL: mongodb://mongo:27017/tailchat_ep
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ep.rule=PathPrefix(`/ep/`)"
      - "traefik.http.services.ep.loadbalancer.server.port=9001"
      - "traefik.http.middlewares.ep-prefix.stripprefix.prefixes=/ep/"
      - "traefik.http.routers.ep.middlewares=ep-prefix"
    networks:
      - tailchat

networks:
  tailchat:
    external:
      name: tailchat-internal
